### ISSUE TITLE
bugged on kodi 19 and also on kodi 20...when it will be finally fixed...??...

### ISSUE THREAD

**Issue by p060477** [fr33p0rt/kodi-plugin.video.com.pornky#6] opened 2023-08-01 08:57 UTC
no way to use this add on
not on kodi 19
also not on kodi 20
when it will be finally fixed...??

**Comment by fr33p0rt** [comment] 2023-08-03 18:36
Version 0.9.8 works for me.

Is page working in common browser, e.g. in Firefox? What is your addon version? 0.9.8 is the latest.

_Have you ever supported the development of this addon with a donation?_

**Comment by p060477** [comment] 2023-08-03 19:10
hi and thxs for reply
the problem is the vpn...without works...with not work at all....
and using a vpn moreover in these sites it is duly reccomended... ;)

**Comment by fr33p0rt** [comment] 2023-08-03 19:25
Not a bug, VPN issue, closing now

**Closed as completed by fr33p0rt** 2023-08-03 19:25 UTC
Labels: invalid

**Comment by p060477** [comment] 2023-08-03 19:29
...consider that it is one of the very very few that does not work with vpn.....
and if it is not a bug...it is very very close to....
;)
